name: Build news.json & BTC Price & Publish

on:
  schedule:
    # 12:10 e 22:10 UTC â‰ˆ 09:10 e 19:10 BRT
    - cron: "10 12 * * *"
    - cron: "10 22 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    env:
      TZ: America/Sao_Paulo
      NEWS_LIMIT: 10
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install psycopg[binary]==3.2.1 requests==2.32.3

      - name: Build news.json
        env:
          DATABASE_URL_READONLY: ${{ secrets.DATABASE_URL_READONLY }}
          NEWS_LIMIT: ${{ env.NEWS_LIMIT }}
        run: python scripts/build_json.py

      - name: Build BTC price (USD)
        run: python scripts/get_btc_price.py

      - uses: actions/upload-pages-artifact@v3
        with:
          path: public

      - uses: actions/deploy-pages@v4
